# App name
name: My Web App

# App version
version: 1.0.0

# App description
description: A web app for generic purposes

# App environment
environment: production

# App routes
routes:
  - path: /
    component: Home
  - path: /about
    component: About
  - path: /contact
    component: Contact
